apiVersion: extensions/v1beta1
kind : Deployment
metadata: 
  name: celery-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: celery
 
    spec:
      containers:
      - name: celery-worker
        image: bseenu/celery.srini
        volumeMounts:
        - mountPath: /app/data
          name: data-volume
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: sqlite-pvc 

              
